import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {useReducedMotion} from 'motion/react';
import {FiArrowUpRight, FiDownload, FiGithub, FiLinkedin, FiMail, FiCode, FiLayers, FiServer, FiSmartphone, FiDatabase, FiTool, FiCpu, FiMapPin, FiExternalLink} from 'react-icons/fi';
import MagicBento from './components/MagicBento';
import ProfileCard from './components/ProfileCard';
import Carousel from './components/Carousel';
import './style.css';

const projects = [
 {id:'little-lies',title:'Little Lies',category:'REAL-TIME · MULTIPLAYER GAME',icon:FiCpu,description:'Good friends. Great stories. Convincing lies.',body:'A party game for 3–8 players. Join from your own phone, spot the truth, bluff your friends, and guess who shared each personal story.',points:['Synchronized rooms, timed voting, and live leaderboards','Three guessing rounds plus a story round with point wagers'],stack:['JavaScript','Node.js','WebSockets'],flow:['Join a room','Truth or bluff?','Story showdown'],demo:'https://little-lies.nks0301.chatgpt.site/'},
 {id:'nutritwin',title:'NutriTwin',category:'MOBILE · WELLNESS & AI',icon:FiSmartphone,description:'A little more insight into everyday health.',body:'A cross-platform wellness companion that connects meal tracking, fitness data, and personalized recommendations.',points:['Google Fit and Apple Health synchronization','Gemini-powered nutrition and wellness insights'],stack:['React Native','Firebase','Gemini AI'],flow:['Health data','Personal insights','Daily habits']},
 {id:'campus',title:'Campus Dwellers',category:'FULL STACK · CAMPUS JOBS',icon:FiLayers,description:'Helping students find their next opportunity.',body:'A UGA job platform that brings campus listings and resume matching into one place.',points:['JWT authentication and protected API routes','Resume parsing and automated job aggregation'],stack:['Next.js','TypeScript','Node.js','MongoDB'],flow:['Campus listings','Resume matching','Opportunities'],url:'https://github.com/naveenseedani21/Web-Development-Job-Board'},
 {id:'gilded',title:'The Gilded Page',category:'FULL STACK · ECOMMERCE',icon:FiCode,description:'From the next good read to a completed order.',body:'An online bookstore with customer accounts, shopping and checkout, and a real-time admin dashboard.',points:['Inventory, orders, and promotions in one workflow','EmailJS confirmations and customer notifications'],stack:['JavaScript','Firebase','EmailJS'],flow:['Browse books','Secure checkout','Order updates']},
 {id:'rideshare',title:'UGA RideShare',category:'ANDROID · CAMPUS MOBILITY',icon:FiMapPin,description:'Better ways to get around campus.',body:'A native Android carpool app connecting university drivers and passengers through live ride coordination.',points:['Role-based access for drivers and passengers','Ride requests, real-time updates, and local persistence'],stack:['Java','Android','Firestore','SQLite'],flow:['Post a ride','Find a match','Travel together']},
 {id:'wibecheck',title:'WibeCheck',category:'HACKATHON · MUSIC & AI',icon:FiCpu,description:'A soundtrack for the way you feel.',body:'A mood-based music experience that connects facial emotion detection with personalized Spotify playlists.',points:['Luxand-powered image emotion recognition','API authentication and asynchronous feedback'],stack:['React','Vite','Luxand API','Spotify API'],flow:['Photo check-in','Emotion detection','Mood playlist']}
];
const roles = [
 {id:'handshake',logo:'/handshake-ai.jpeg',company:'Handshake AI',title:'AI Model Evaluator',date:'JAN 2026 — PRESENT',location:'Remote',mark:'H',description:'Helping make AI systems more useful, reliable, and grounded.',points:['Evaluate frontier LLMs on software engineering and multimodal reasoning tasks.','Identify failure modes in generated image outputs and provide actionable feedback.','Apply structured rubrics and maintain consistent evaluation standards.'],tags:['AI evaluation','Code quality','Human feedback']},
 {id:'skyit',logo:'/skyit.png',company:'SkyIT Services',title:'Software Engineering Intern',date:'MAY — AUG 2024',location:'Remote · Backend',mark:'S',description:'Improving the systems behind everyday product workflows.',points:['Developed Node.js services and migrated data to Azure MySQL, improving query speeds by about 40%.','Built and tested REST APIs for correctness and performance.','Validated backend functionality across 20+ release cycles.'],tags:['Node.js','REST APIs','Azure MySQL']},
 {id:'uga',logo:'/uga-housing.jpeg',company:'University of Georgia',title:'Resident Assistant',date:'AUG 2024 — MAY 2025',location:'Athens, Georgia',mark:'G',description:'Good engineering starts with understanding people.',points:['Supported a community of 30+ residents.','Coordinated 10+ community events and helped connect residents with campus resources.','Maintained safety and supported constructive conflict resolution.'],tags:['Leadership','Communication','Community']},
 {id:'marble',company:'Marble Slab Creamery',title:'Shift Manager',date:'SEP 2022 — JUL 2023',location:'Stafford, Texas',mark:'M',description:'Keeping a busy team and its daily operations moving.',points:['Trained and supervised three new employees.','Managed daily operations and cash workflows exceeding $3,000.','Improved order processing efficiency by 25% through better workflows and team coordination.'],tags:['Teamwork','Operations','Problem solving']}
];
const branches=[
 {id:'frontend',name:'Frontend',icon:FiLayers,skills:['React','Next.js','TypeScript','JavaScript'],note:'Interfaces that make complex workflows feel simple.'},
 {id:'backend',name:'Backend',icon:FiServer,skills:['Node.js','Express','Java','Python','REST APIs'],note:'Reliable APIs, useful integrations, and dependable systems.'},
 {id:'mobile',name:'Mobile',icon:FiSmartphone,skills:['Android','React Native','Kotlin','Java'],note:'Native and cross-platform experiences built around daily life.'},
 {id:'data',name:'Databases',icon:FiDatabase,skills:['Firebase','SQL / MySQL','MongoDB','SQLite'],note:'Data models and synchronization that keep products connected.'},
 {id:'tools',name:'Systems & tools',icon:FiTool,skills:['Git','Linux','AWS','C / C++','Postman'],note:'A foundation in systems, debugging, and collaborative development.'}
];
function PanelHeading({number,title,aside}){return <div className="panel-heading"><h2><span>{number}</span>{title}</h2>{aside && <span className="panel-aside">{aside}</span>}</div>}
function SkillTree(){const [selected,setSelected]=useState('backend');const branch=branches.find(b=>b.id===selected);return <section id="skills" className="skill-content"><PanelHeading number="02" title="A connected skill set" aside="SELECT A BRANCH"/><div className="skill-tree"><div className="tree-root"><FiCode/><span>Full stack engineering</span></div><div className="branches">{branches.map(b=><button className={`branch ${selected===b.id?'selected':''}`} key={b.id} aria-pressed={selected===b.id} onClick={()=>setSelected(b.id)}><b.icon/><span>{b.name}</span></button>)}</div></div><div className="branch-detail" aria-live="polite"><div className="skill-list">{branch.skills.map(s=><span key={s}>{s}</span>)}</div><p>{branch.note}</p></div></section>}
function ResponsiveCarousel({items,label,renderItem,reducedMotion}){const ref=useRef(null);const [width,setWidth]=useState(300);useEffect(()=>{const observer=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));if(ref.current)observer.observe(ref.current);return()=>observer.disconnect()},[]);return <div ref={ref} className="carousel-space"><Carousel items={items} baseWidth={width} label={label} renderItem={renderItem} reducedMotion={reducedMotion}/></div>}
function ProjectSlide(p){const Icon=p.icon;return <article className="project-slide"><div className="slide-eyebrow"><Icon/><span>{p.category}</span></div><h3>{p.title}</h3><p className="project-strap">{p.description}</p><div className="project-flow" aria-label={`${p.title} workflow`}>{p.flow.map((step,i)=><React.Fragment key={step}>{i>0&&<span className="flow-line" aria-hidden="true"/>}<span className="flow-node"><span className="flow-number">0{i+1}</span>{step}</span></React.Fragment>)}</div><p className="slide-body">{p.body}</p><ul className="project-points">{p.points.map(x=><li key={x}>{x}</li>)}</ul><div className="slide-bottom"><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div>{p.demo&&<a className="source-link" href={p.demo} target="_blank" rel="noreferrer">Play Little Lies <FiArrowUpRight/></a>}{p.url&&<a className="source-link" href={p.url} target="_blank" rel="noreferrer">View source <FiArrowUpRight/></a>}</div></article>}
function RoleSlide(r){return <article className="role-slide"><div className="role-meta"><span className={`company-mark company-${r.id}`}>{r.logo?<img src={r.logo} alt={`${r.company} logo`}/>:r.mark}</span><div><p className="company-name">{r.company}</p><p className="role-location">{r.location}</p></div></div><div className="role-date">{r.date}</div><h3>{r.title}</h3><p className="role-intro">{r.description}</p><ul className="role-points">{r.points.map(p=><li key={p}>{p}</li>)}</ul><div className="tags">{r.tags.map(t=><span key={t}>{t}</span>)}</div></article>}
function App(){const reducedMotion=useReducedMotion();return <div className="site-shell" id="top"><a className="skip-link" href="#portfolio">Skip to portfolio</a><header className="topbar"><a className="wordmark" href="#top" aria-label="Naveen Seedani, home">n<span>s</span><i>.</i></a><nav aria-label="Main navigation"><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#about">About</a></nav><a className="header-contact" href="mailto:naveenseedani16@gmail.com">Let’s talk <FiArrowUpRight/></a></header><main id="portfolio"><div className="intro"><div><p className="eyebrow">NAVEEN SEEDANI / SOFTWARE ENGINEER</p><h1>Useful software. <span>Thoughtfully built.</span></h1></div><div className="intro-right"><p>Full stack, backend, mobile.<br/>A curiosity for what comes next.</p><span className="availability"><i/>Open to opportunities</span></div></div><MagicBento disableAnimations={reducedMotion} cards={[
 {id:'profile',content:<><ProfileCard avatarUrl="/portrait.png" name="Naveen Seedani" title="Software Engineer" handle="naveenseedani" iconUrl="" grainUrl="" enableTilt={!reducedMotion} behindGlowEnabled={false}/></>},
 {id:'skills',content:<SkillTree/>},
 {id:'about',content:<section id="about" className="about-content"><PanelHeading number="01" title="The person behind the code"/><h2 className="about-title">Curious by default.<br/><span>Practical by design.</span></h2><p>I’m Naveen, a software engineer based in Austin. I build full stack products, backend systems, and mobile apps that solve everyday problems.</p><p>I’m especially interested in useful AI applications—and understanding where the models behind them succeed or fall short.</p><div className="education"><span className="education-mark">G</span><div><strong>University of Georgia</strong><span>B.S. Computer Science · 2025</span></div></div><div className="about-actions"><a className="resume-link" href="/Naveen-Seedani-Resume.pdf" download><FiDownload/>Resume</a><div className="socials"><a href="https://github.com/naveenseedani21" target="_blank" rel="noreferrer" aria-label="GitHub"><FiGithub/></a><a href="https://linkedin.com/in/naveen-seedani/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><FiLinkedin/></a><a href="mailto:naveenseedani16@gmail.com" aria-label="Email Naveen"><FiMail/></a></div></div></section>},
 {id:'projects',content:<section id="projects" className="carousel-panel"><PanelHeading number="03" title="Selected projects" aside={`${String(projects.length).padStart(2,'0')} PROJECTS`}/><ResponsiveCarousel items={projects} label="Projects" renderItem={ProjectSlide} reducedMotion={reducedMotion}/></section>},
 {id:'experience',content:<section id="experience" className="carousel-panel"><PanelHeading number="04" title="Experience" aside="04 ROLES"/><ResponsiveCarousel items={roles} label="Experience" renderItem={RoleSlide} reducedMotion={reducedMotion}/></section>}
 ]}/></main><footer id="contact"><div><span className="footer-invite">Have something in mind?</span><a href="mailto:naveenseedani16@gmail.com">Let’s build something useful. <FiArrowUpRight/></a></div><div className="footer-meta"><span>Austin, Texas</span><span>© {new Date().getFullYear()} Naveen Seedani</span></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
